# Generated by Django 5.2.4 on 2025-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the event.', max_length=200)),
                ('event_date', models.DateTimeField(blank=True, help_text='The date and time of the event (optional).', null=True)),
                ('foo', models.CharField(blank=True, help_text='foo', max_length=200, null=True, unique=True)),
            ],
        ),
    ]
